# Site settings
title: Carlos Mota
description: >-
  Android tech lead at WIT Software, he can easily be spotted there working on the company RCS solution. An enthusiastic for new technology and always trying to reach those last 20% of all of his side projects that seem to be really far away, he loves to share his knowledge with others either by giving talks, teaching, writing or along with a cold beer in the nearest pub. GDG Coimbra organizer and Kotlin evangelist, he also has a huge passion for travel, photography, space and the occasional run.
lang: en-US
timezone: Europe/Lisbon
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/cmota
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Carlos Mota
  bio: 
    </p>
    👨‍💻 Android Dev Lead @WITSoftware </p>
    🗣 Founder <a href="https://twitter.com/GDGCoimbra" target="_blank" rel="noopener">@GDGCoimbra</a> and co-founder <a href="https://twitter.com/Kotlin_Knights" target="_blank" rel="noopener">@Kotlin_Knights</a> </p>
    ✍️ Author <a href="https://twitter.com/rwenderlich" target="_blank" rel="noopener">@rwenderlich</a> and <a href="https://twitter.com/opinioesonline" target="_blank" rel="noopener">@opinioesonline</a> </p>
    🎙 Podcaster wannabe </p>
    🗺 Loves travel, photography and running </p>

  username: cafonsomota
  email: cafonsomota@gmail.com
  avatar: /assets/img/avatar.jpg

# Url settings
url: "https://cafonsomota.xyz"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true
  talks:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

future: true

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
